image: docker:stable

before_script:
  - apk update && apk add git
  - git --version

stages:
  - my_services_cloud
  - apache-php



Job-my_services_cloud:
  stage: my_services_cloud
  tags: 
    - runner1
    - my_services_cloud
  only:
    - tags
  script:
    - docker rm -f my_services_cloud && docker rmi -f gorinel/my_services_cloud
    - docker build https://github.com/gwendal-orinel/docker.git#master:my_services_cloud -t gorinel/my_services_cloud
    - docker run -d --name=my_services_cloud -h my_services_cloud --restart=always -p 80:80 -p 8080:443 gorinel/my_services_cloud
   
   
 
Job-apache-php:
  stage: apache-php
  tags:
    - runner1
    - apache-php
  only:
    - tags
  script:
    - docker build https://github.com/gwendal-orinel/docker.git#master:apache-php -t gorinel/apache-php
    - docker run -d --name=apache-php -h apache-php --restart=always gorinel/apache-php
