image: docker:stable

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build https://github.com/gwendal-orinel/docker.git#master:my_services_cloud -t gorinel/my_services_cloud
