image: docker:stable

before_script:
  - apk update && apk add git
  - git --version

build:
  stage: build
  tags: 
    - runner1
  script:
    - docker build https://github.com/gwendal-orinel/docker.git#master:apache-php -t gorinel/apache-php
    - docker run -d --name=apache-php -h apache-php --restart=always -p 80:80 -p 443:443 gorinel/apache-php
