image: docker:stable

before_script:
  - apk update && apk add git
  - git --version

build:
  stage: build
  tags: 
    - runner1
  script:
    - docker info
    - docker build https://github.com/gwendal-orinel/docker.git#master:my_services_cloud -t gorinel/my_services_cloud
