image: docker:stable

build:
  stage: build
  tags: 
    - runner1
  script:
    - /usr/bin/git --help
    - docker info
    - docker build https://github.com/gwendal-orinel/docker.git#master:my_services_cloud -t gorinel/my_services_cloud
