image: docker:stable

tags: 
    - runner1

before_script:
  - export DOCKER_HOST=$DOCKER_PORT
  - docker info

build:
  stage: build
  script:
    - docker build https://github.com/gwendal-orinel/docker.git#master:my_services_cloud -t gorinel/my_services_cloud
